name: Run PHP Unit Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: PHPUnit Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: userpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Wait for MySQL
        run: |
          sudo apt-get install -y netcat
          until nc -z 127.0.0.1 3306; do
            echo "Waiting for MySQL to be ready..."
            sleep 3
          done

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration src/phpunit.xml
